# Generated by Django 3.2.4 on 2021-07-25 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oursystem.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(auto_created=True, max_length=7, unique=True)),
                ('course_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('section', models.PositiveSmallIntegerField(verbose_name='Section no.')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to=oursystem.models.save_course_files, verbose_name='Video')),
                ('ppt', models.FileField(blank=True, upload_to=oursystem.models.save_course_files, verbose_name='Presentations')),
                ('pdf', models.FileField(blank=True, upload_to=oursystem.models.save_course_files, verbose_name='pdf')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='oursystem.subject')),
            ],
            options={
                'ordering': ['section'],
            },
        ),
    ]
