# Generated by Django 3.2.4 on 2021-08-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oursystem', '0002_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Section no.'),
        ),
    ]
