# Generated by Django 3.2.4 on 2021-08-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oursystem', '0003_auto_20210825_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.PositiveSmallIntegerField(verbose_name='Section no.'),
        ),
    ]
