# Generated by Django 4.2 on 2023-04-14 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oursystem', '0004_alter_course_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code']},
        ),
    ]
